version: '3.1'

services:
  db:
    image: mysql:8
   
    ports:
      - 3304:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pagamento
    volumes:
      - /home/curso1/docker:/var/lib/mysql
volumes:
  mysql_data:
    driver: local